package com.doozi.scorena.communication;

public enum NotificationTypeEnum {
	NEW_CUSTOM_QUESTION, GAMERESULT, NEW_COMMENT, NEW_FOLLOW, FRIENDBET, INACTIVE_USER_REMINDER, TOURNAMENT_INVITATION, TOURNAMENT_ACCEPTANCE
}
